const PuzzleData = [
  {
    "AnswerURL": null,
    "Arc": "",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "Four O'Clock",
    "PuzzleId": 29439,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/FourOClock.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Door",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "The Jeopardy Room (Black Lock)",
    "PuzzleId": 29442,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/TheJeopardyRoom-BlackLock.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Door",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "The Jeopardy Room (Blue Lock)",
    "PuzzleId": 29445,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/TheJeopardyRoom-BlueLock.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Door",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "The Jeopardy Room (Gold Lock)",
    "PuzzleId": 29444,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/TheJeopardyRoom-GoldLock.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Door",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "The Jeopardy Room (Green Lock)",
    "PuzzleId": 29443,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/TheJeopardyRoom-GreenLock.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Door",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "The Jeopardy Room (Pink Lock)",
    "PuzzleId": 29446,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/TheJeopardyRoom-PinkLock.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Door",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "The Jeopardy Room (Red Hasp)",
    "PuzzleId": 29378,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/PH18/TheJeopardyRoom-RedHasp.aspx",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Door",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "The Jeopardy Room (Violet Lock)",
    "PuzzleId": 29447,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/TheJeopardyRoom-VioletLock.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Door",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "The World Next Door",
    "PuzzleId": 29393,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/TheWorldNextDoor.pdf",
    "WhenSolvable": "2017-09-08T18:03:08.0560582Z",
    "SolvedAt": "2017-09-08T18:51:19.3238792Z",
    "Order": null,
    "Solved": true
  },
  {
    "AnswerURL": null,
    "Arc": "E=mc^2",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "Execution",
    "PuzzleId": 29397,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/Execution.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "E=mc^2",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "Shatterday",
    "PuzzleId": 29400,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/Shatterday.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Eye",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "Aqua Vita",
    "PuzzleId": 29403,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/AquaVita.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Eye",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "Eye of the Beholder",
    "PuzzleId": 29405,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/Eye of the Beholder.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Figure",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "Person or Persons Unknown",
    "PuzzleId": 29415,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/PersonOrPersonsUnknown.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Figure",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "To Serve Man",
    "PuzzleId": 29419,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/ToServeMan.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Funnel",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "The Misfortune Cookie",
    "PuzzleId": 29426,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/TheMisfortuneCookie-Beta.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Funnel",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "The Parallel",
    "PuzzleId": 29427,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/TheParallel.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Hourglass",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "A Nice Place to Visit",
    "PuzzleId": 29383,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/ANicePlaceToVisit.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Hourglass",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "A World of Difference",
    "PuzzleId": 29384,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/AWorldOfDifference.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Window",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "It's a Good Life",
    "PuzzleId": 29431,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/ItsAGoodLife.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  },
  {
    "AnswerURL": null,
    "Arc": "Window",
    "IsInEmailMode": false,
    "IsMetaPuzzle": false,
    "Location": null,
    "PuzzleName": "Little Boy Lost",
    "PuzzleId": 29432,
    "Round": null,
    "Token": null,
    "UpdatedThreads": 0,
    "PuzzleURL": "https://puzzlehunt.localtest.me:44300/Puzzles/Little Boy Lost.pdf",
    "WhenSolvable": "2017-09-08T18:51:19.3263809Z",
    "SolvedAt": null,
    "Order": null,
    "Solved": false
  }
];

export { PuzzleData };
